# Configuration file for connecting Spring Boot to MySQL database
spring.application.name=food-ordering-system

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/food_ordering_system
spring.datasource.username=root
spring.datasource.password=Renne
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8085
